github:
 user: ""
 token: ""
 secret: ""

service:
  type: ClusterIP

ingress:
  enabled: true
  ingressClassName: traefik-ext
  annotations:
    traefik.ingress.kubernetes.io/middleware:  whitelisted-github-ips
  path: /*
  hosts:
    - host: # TBD
      paths: ["/"]
      service: atlantis
  tls: []

resources:
  requests:
   memory: 1Gi
   cpu: 100m
  limits:
   memory: 1Gi
   cpu: 100m

replicaCount: 1

repoConfig: |
  repos:
  - id: "/.*/"
    apply_requirements:
    - approved
    allowed_overrides:
    - apply_requirements

allowDraftPRs: false

hidePrevPlanComments: true

disableRepoLocking: false

## Optionally, so UI wouldn't be exposed passwordless, even though will be accesible only through VPN
#basicAuth:
#  username: "atlantis"
#  password: "atlantis"
